app:
  name: 'Wildberris level 0'
  version: '1.0.0'

postgres:
  host: '127.0.0.1'
  port: '5588'
  user: 'wb_admin'
  password: 'postgres'
  name: 'postgres'
  pg_driver: 'pgx'

http:
  host: '0.0.0.0'
  port: '11000'

nats:
  host: 'localhost'
  port: '4222'
  cluster: 'test-cluster'
  client: 'test-client'
  topic: 'test-topic'
